# Generated by Django 3.2.25 on 2025-07-03 23:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('length', models.FloatField()),
            ],
        ),
    ]
