# Generated by Django 3.2.25 on 2025-07-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='Velocity_Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_value', models.FloatField()),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_reads', to='core.road')),
            ],
        ),
    ]
