# Generated by Django 3.2.25 on 2025-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_velocity_reads'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='name',
            field=models.CharField(default='asdadad', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='velocity_reads',
            name='read_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
