# Generated by Django 3.2.25 on 2025-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250706_1354'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='road',
            constraint=models.UniqueConstraint(fields=('name', 'segment'), name='unique_road'),
        ),
    ]
