# Generated by Django 3.2.25 on 2025-07-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_road_unique_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
