# Generated by Django 3.2.25 on 2025-07-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plates_Reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField()),
                ('car_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='core.car')),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road', to='core.road')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sensor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('license_plate',), name='unique_license_plate'),
        ),
    ]
